repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 26.3.1
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v22.1.1
  hooks:
    - id: clang-format
      exclude: \.json$
