load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "fps_regulator",
    srcs = [],
    hdrs = ["fps_regulator.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "frontend",
    srcs = [],
    hdrs = [
        "frontend.h",
        "headless.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//gbemu/backend",
        "@sdl2//:SDL2",
    ],
)
