#ifndef GBEMU_BACKEND_OPCODE_DATA_H
#define GBEMU_BACKEND_OPCODE_DATA_H

#include "gbemu/backend/opcode.h"

namespace gbemu::backend
{

// Shorthand aliases for opcode data definitions.
using F = OPCode::Flag;
using J = OPCode::JumpCondition;
using R = Register;
using FR = FullRegister;
using SR = SpecialRegister;
using DR = DereferencedFullRegister;
static constexpr auto _ = F::UNTOUCHED;

// clang-format off
static constexpr std::array<OPCode, 256> OPCODES = {
    {{0x00, "NOP", "NOP", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x01, "LD BC, d16", "LD", {{FR::BC, {}}}, 1, {{{}, {}}}, 0, 3, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x02, "LD (BC), A", "LD", {{DR{FR::BC}, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x03, "INC BC", "INC", {{FR::BC, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x04, "INC B", "INC", {{R::B, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x05, "DEC B", "DEC", {{R::B, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x06, "LD B, d8", "LD", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x07, "RLCA", "RLCA", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::ZERO, F::A7}}, true},
     {0x08, "LD (a16), SP", "LD_SP", {{SR::SP, {}}}, 1, {{{}, {}}}, 0, 3, 5, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x09, "ADD HL, BC", "ADD", {{FR::HL, FR::BC}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, F::ZERO, F::H, F::CY}}, true},
     {0x0a, "LD A, (BC)", "LD", {{R::A, DR{FR::BC}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x0b, "DEC BC", "DEC", {{FR::BC, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x0c, "INC C", "INC", {{R::C, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x0d, "DEC C", "DEC", {{R::C, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x0e, "LD C, d8", "LD", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x0f, "RRCA", "RRCA", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::ZERO, F::A0}}, true},
     {0x10, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0x11, "LD DE, d16", "LD", {{FR::DE, {}}}, 1, {{{}, {}}}, 0, 3, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x12, "LD (DE), A", "LD", {{DR{FR::DE}, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x13, "INC DE", "INC", {{FR::DE, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x14, "INC D", "INC", {{R::D, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x15, "DEC D", "DEC", {{R::D, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x16, "LD D, d8", "LD", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x17, "RLA", "RLA", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::ZERO, F::A7}}, true},
     {0x18, "JR s8", "JR", {{{}, {}}}, 0, {{{}, {}}}, 0, 2, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x19, "ADD HL, DE", "ADD", {{FR::HL, FR::DE}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, F::ZERO, F::H, F::CY}}, true},
     {0x1a, "LD A, (DE)", "LD", {{R::A, DR{FR::DE}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x1b, "DEC DE", "DEC", {{FR::DE, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x1c, "INC E", "INC", {{R::E, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x1d, "DEC E", "DEC", {{R::E, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x1e, "LD E, d8", "LD", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x1f, "RRA", "RRA", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::ZERO, F::A0}}, true},
     {0x20, "JR NZ, s8", "JR", {{{}, {}}}, 0, {{{}, {}}}, 0, 2, 2, 1, J::NZ, {{_, _, _, _}}, true},
     {0x21, "LD HL, d16", "LD", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 3, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x22, "LD (HL+), A", "LDI", {{DR{FR::HL}, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x23, "INC HL", "INC", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x24, "INC H", "INC", {{R::H, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x25, "DEC H", "DEC", {{R::H, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x26, "LD H, d8", "LD", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x27, "DAA", "DAA", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, _, F::ZERO, F::CY}}, true},
     {0x28, "JR Z, s8", "JR", {{{}, {}}}, 0, {{{}, {}}}, 0, 2, 2, 1, J::Z, {{_, _, _, _}}, true},
     {0x29, "ADD HL, HL", "ADD", {{FR::HL, FR::HL}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, F::ZERO, F::H, F::CY}}, true},
     {0x2a, "LD A, (HL+)", "LDI", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x2b, "DEC HL", "DEC", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x2c, "INC L", "INC", {{R::L, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x2d, "DEC L", "DEC", {{R::L, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x2e, "LD L, d8", "LD", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x2f, "CPL", "CPL", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, F::ONE, F::ONE, _}}, true},
     {0x30, "JR NC, s8", "JR", {{{}, {}}}, 0, {{{}, {}}}, 0, 2, 2, 1, J::NC, {{_, _, _, _}}, true},
     {0x31, "LD SP, d16", "LD", {{SR::SP, {}}}, 1, {{{}, {}}}, 0, 3, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x32, "LD (HL-), A", "LDD", {{DR{FR::HL}, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x33, "INC SP", "INC", {{SR::SP, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x34, "INC (HL)", "INC", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x35, "DEC (HL)", "DEC", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x36, "LD (HL), d8", "LD", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x37, "SCF", "SCF", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, F::ZERO, F::ZERO, F::ONE}}, true},
     {0x38, "JR C, s8", "JR", {{{}, {}}}, 0, {{{}, {}}}, 0, 2, 2, 1, J::C, {{_, _, _, _}}, true},
     {0x39, "ADD HL, SP", "ADD", {{FR::HL, SR::SP}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, F::ZERO, F::H, F::CY}}, true},
     {0x3a, "LD A, (HL-)", "LDD", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x3b, "DEC SP", "DEC", {{SR::SP, {}}}, 1, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x3c, "INC A", "INC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, _}}, true},
     {0x3d, "DEC A", "DEC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, _}}, true},
     {0x3e, "LD A, d8", "LD", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x3f, "CCF", "CCF", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, F::ZERO, F::ZERO, F::NOT_CY}}, true},
     {0x40, "LD B, B", "LD", {{R::B, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x41, "LD B, C", "LD", {{R::B, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x42, "LD B, D", "LD", {{R::B, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x43, "LD B, E", "LD", {{R::B, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x44, "LD B, H", "LD", {{R::B, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x45, "LD B, L", "LD", {{R::B, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x46, "LD B, (HL)", "LD", {{R::B, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x47, "LD B, A", "LD", {{R::B, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x48, "LD C, B", "LD", {{R::C, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x49, "LD C, C", "LD", {{R::C, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4a, "LD C, D", "LD", {{R::C, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4b, "LD C, E", "LD", {{R::C, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4c, "LD C, H", "LD", {{R::C, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4d, "LD C, L", "LD", {{R::C, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4e, "LD C, (HL)", "LD", {{R::C, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x4f, "LD C, A", "LD", {{R::C, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x50, "LD D, B", "LD", {{R::D, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x51, "LD D, C", "LD", {{R::D, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x52, "LD D, D", "LD", {{R::D, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x53, "LD D, E", "LD", {{R::D, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x54, "LD D, H", "LD", {{R::D, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x55, "LD D, L", "LD", {{R::D, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x56, "LD D, (HL)", "LD", {{R::D, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x57, "LD D, A", "LD", {{R::D, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x58, "LD E, B", "LD", {{R::E, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x59, "LD E, C", "LD", {{R::E, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5a, "LD E, D", "LD", {{R::E, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5b, "LD E, E", "LD", {{R::E, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5c, "LD E, H", "LD", {{R::E, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5d, "LD E, L", "LD", {{R::E, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5e, "LD E, (HL)", "LD", {{R::E, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x5f, "LD E, A", "LD", {{R::E, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x60, "LD H, B", "LD", {{R::H, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x61, "LD H, C", "LD", {{R::H, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x62, "LD H, D", "LD", {{R::H, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x63, "LD H, E", "LD", {{R::H, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x64, "LD H, H", "LD", {{R::H, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x65, "LD H, L", "LD", {{R::H, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x66, "LD H, (HL)", "LD", {{R::H, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x67, "LD H, A", "LD", {{R::H, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x68, "LD L, B", "LD", {{R::L, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x69, "LD L, C", "LD", {{R::L, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6a, "LD L, D", "LD", {{R::L, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6b, "LD L, E", "LD", {{R::L, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6c, "LD L, H", "LD", {{R::L, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6d, "LD L, L", "LD", {{R::L, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6e, "LD L, (HL)", "LD", {{R::L, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x6f, "LD L, A", "LD", {{R::L, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x70, "LD (HL), B", "LD", {{DR{FR::HL}, R::B}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x71, "LD (HL), C", "LD", {{DR{FR::HL}, R::C}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x72, "LD (HL), D", "LD", {{DR{FR::HL}, R::D}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x73, "LD (HL), E", "LD", {{DR{FR::HL}, R::E}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x74, "LD (HL), H", "LD", {{DR{FR::HL}, R::H}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x75, "LD (HL), L", "LD", {{DR{FR::HL}, R::L}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x76, "HALT", "HALT", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x77, "LD (HL), A", "LD", {{DR{FR::HL}, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x78, "LD A, B", "LD", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x79, "LD A, C", "LD", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7a, "LD A, D", "LD", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7b, "LD A, E", "LD", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7c, "LD A, H", "LD", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7d, "LD A, L", "LD", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7e, "LD A, (HL)", "LD", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x7f, "LD A, A", "LD", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x80, "ADD A, B", "ADD", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x81, "ADD A, C", "ADD", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x82, "ADD A, D", "ADD", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x83, "ADD A, E", "ADD", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x84, "ADD A, H", "ADD", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x85, "ADD A, L", "ADD", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x86, "ADD A, (HL)", "ADD", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x87, "ADD A, A", "ADD", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x88, "ADC A, B", "ADC", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x89, "ADC A, C", "ADC", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8a, "ADC A, D", "ADC", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8b, "ADC A, E", "ADC", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8c, "ADC A, H", "ADC", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8d, "ADC A, L", "ADC", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8e, "ADC A, (HL)", "ADC", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x8f, "ADC A, A", "ADC", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0x90, "SUB A, B", "SUB", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x91, "SUB A, C", "SUB", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x92, "SUB A, D", "SUB", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x93, "SUB A, E", "SUB", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x94, "SUB A, H", "SUB", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x95, "SUB A, L", "SUB", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x96, "SUB A, (HL)", "SUB", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x97, "SUB A, A", "SUB", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x98, "SBC A, B", "SBC", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x99, "SBC A, C", "SBC", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9a, "SBC A, D", "SBC", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9b, "SBC A, E", "SBC", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9c, "SBC A, H", "SBC", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9d, "SBC A, L", "SBC", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9e, "SBC A, (HL)", "SBC", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0x9f, "SBC A, A", "SBC", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xa0, "AND A, B", "AND", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa1, "AND A, C", "AND", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa2, "AND A, D", "AND", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa3, "AND A, E", "AND", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa4, "AND A, H", "AND", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa5, "AND A, L", "AND", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa6, "AND A, (HL)", "AND", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa7, "AND A, A", "AND", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xa8, "XOR A, B", "XOR", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xa9, "XOR A, C", "XOR", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xaa, "XOR A, D", "XOR", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xab, "XOR A, E", "XOR", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xac, "XOR A, H", "XOR", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xad, "XOR A, L", "XOR", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xae, "XOR A, (HL)", "XOR", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xaf, "XOR A, A", "XOR", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb0, "OR A, B", "OR", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb1, "OR A, C", "OR", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb2, "OR A, D", "OR", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb3, "OR A, E", "OR", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb4, "OR A, H", "OR", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb5, "OR A, L", "OR", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb6, "OR A, (HL)", "OR", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb7, "OR A, A", "OR", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xb8, "CP A, B", "CP", {{R::A, R::B}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xb9, "CP A, C", "CP", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xba, "CP A, D", "CP", {{R::A, R::D}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xbb, "CP A, E", "CP", {{R::A, R::E}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xbc, "CP A, H", "CP", {{R::A, R::H}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xbd, "CP A, L", "CP", {{R::A, R::L}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xbe, "CP A, (HL)", "CP", {{R::A, DR{FR::HL}}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xbf, "CP A, A", "CP", {{R::A, R::A}}, 2, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xc0, "RET NZ", "RET", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 2, 3, J::NZ, {{_, _, _, _}}, true},
     {0xc1, "POP BC", "POP", {{FR::BC, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc2, "JP NZ, a16", "JP", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 1, J::NZ, {{_, _, _, _}}, true},
     {0xc3, "JP a16", "JP", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc4, "CALL NZ, a16", "CALL", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 3, J::NZ, {{_, _, _, _}}, true},
     {0xc5, "PUSH BC", "PUSH", {{FR::BC, {}}}, 1, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc6, "ADD A, d8", "ADD", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0xc7, "RST 0", "RST", {{{}, {}}}, 0, {{0, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc8, "RET Z", "RET", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 2, 3, J::Z, {{_, _, _, _}}, true},
     {0xc9, "RET", "RET", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xca, "JP Z, a16", "JP", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 1, J::Z, {{_, _, _, _}}, true},
     {0xcb, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xcc, "CALL Z, a16", "CALL", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 3, J::Z, {{_, _, _, _}}, true},
     {0xcd, "CALL a16", "CALL", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 6, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xce, "ADC A, d8", "ADC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::H, F::CY}}, true},
     {0xcf, "RST 1", "RST", {{{}, {}}}, 0, {{1, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd0, "RET NC", "RET", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 2, 3, J::NC, {{_, _, _, _}}, true},
     {0xd1, "POP DE", "POP", {{FR::DE, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd2, "JP NC, a16", "JP", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 1, J::NC, {{_, _, _, _}}, true},
     {0xd3, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xd4, "CALL NC, a16", "CALL", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 3, J::NC, {{_, _, _, _}}, true},
     {0xd5, "PUSH DE", "PUSH", {{FR::DE, {}}}, 1, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd6, "SUB A, D8", "SUB", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xd7, "RST 2", "RST", {{{}, {}}}, 0, {{2, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd8, "RET C", "RET", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 2, 3, J::C, {{_, _, _, _}}, true},
     {0xd9, "RETI", "RETI", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xda, "JP C, a16", "JP", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 1, J::C, {{_, _, _, _}}, true},
     {0xdb, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xdc, "CALL C, a16", "CALL", {{{}, {}}}, 0, {{{}, {}}}, 0, 3, 3, 3, J::C, {{_, _, _, _}}, true},
     {0xdd, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xde, "SBC A, d8", "SBC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xdf, "RST 3", "RST", {{{}, {}}}, 0, {{3, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe0, "LD (a8), A", "LDff8", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe1, "POP HL", "POP", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe2, "LD (C), A", "LDff8", {{R::C, R::A}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe3, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xe4, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xe5, "PUSH HL", "PUSH", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe6, "AND A, d8", "AND", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ONE, F::ZERO}}, true},
     {0xe7, "RST 4", "RST", {{{}, {}}}, 0, {{4, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe8, "ADD SP, s8", "ADD", {{SR::SP, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::H, F::CY}}, true},
     {0xe9, "JP HL", "JP", {{FR::HL, {}}}, 1, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xea, "LD (a16), A", "LDa16", {{R::A, {}}}, 1, {{{}, {}}}, 0, 3, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xeb, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xec, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xed, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xee, "XOR A, d8", "XOR", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xef, "RST 5", "RST", {{{}, {}}}, 0, {{5, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf0, "LD A, (a8)", "LDaff8", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf1, "POP AF", "POP", {{FR::AF, {}}}, 1, {{{}, {}}}, 0, 1, 3, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf2, "LD A, (C)", "LDaff8", {{R::A, R::C}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf3, "DI", "DI", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf4, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xf5, "PUSH AF", "PUSH", {{FR::AF, {}}}, 1, {{{}, {}}}, 0, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf6, "OR A, d8", "OR", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0xf7, "RST 6", "RST", {{{}, {}}}, 0, {{6, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf8, "LD HL, SP+s8", "LDs8", {{FR::HL, SR::SP}}, 2, {{{}, {}}}, 0, 2, 3, 0, J::ALWAYS, {{F::ZERO, F::ZERO, F::H, F::CY}}, true},
     {0xf9, "LD SP, HL", "LD", {{SR::SP, FR::HL}}, 2, {{{}, {}}}, 0, 1, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfa, "LD A, (a16)", "LDaff16", {{R::A, {}}}, 1, {{{}, {}}}, 0, 3, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfb, "EI", "EI", {{{}, {}}}, 0, {{{}, {}}}, 0, 1, 1, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfc, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xfd, "", "", {{{}, {}}}, 0, {{0, 0}}, 0, 0, 0, 0, J::ALWAYS, {{_, _, _, _}}, false},
     {0xfe, "CP A, d8", "CP", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ONE, F::H, F::CY}}, true},
     {0xff, "RST 7", "RST", {{{}, {}}}, 0, {{7, 0}}, 1, 1, 4, 0, J::ALWAYS, {{_, _, _, _}}, true}}};

static constexpr std::array<OPCode, 256> PREFIXED_OPCODES = {
    {{0x00, "RLC B", "RLC", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x01, "RLC C", "RLC", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x02, "RLC D", "RLC", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x03, "RLC E", "RLC", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x04, "RLC H", "RLC", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x05, "RLC L", "RLC", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x06, "RLC (HL)", "RLC", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x07, "RLC A", "RLC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x08, "RRC B", "RRC", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x09, "RRC C", "RRC", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0a, "RRC D", "RRC", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0b, "RRC E", "RRC", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0c, "RRC H", "RRC", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0d, "RRC L", "RRC", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0e, "RRC (HL)", "RRC", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x0f, "RRC A", "RRC", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x10, "RL B", "RL", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x11, "RL C", "RL", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x12, "RL D", "RL", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x13, "RL E", "RL", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x14, "RL H", "RL", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x15, "RL L", "RL", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x16, "RL (HL)", "RL", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x17, "RL A", "RL", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x18, "RR B", "RR", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x19, "RR C", "RR", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1a, "RR D", "RR", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1b, "RR E", "RR", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1c, "RR H", "RR", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1d, "RR L", "RR", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1e, "RR (HL)", "RR", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x1f, "RR A", "RR", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x20, "SLA B", "SLA", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x21, "SLA C", "SLA", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x22, "SLA D", "SLA", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x23, "SLA E", "SLA", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x24, "SLA H", "SLA", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x25, "SLA L", "SLA", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x26, "SLA (HL)", "SLA", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x27, "SLA A", "SLA", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A7}}, true},
     {0x28, "SRA B", "SRA", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x29, "SRA C", "SRA", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2a, "SRA D", "SRA", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2b, "SRA E", "SRA", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2c, "SRA H", "SRA", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2d, "SRA L", "SRA", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2e, "SRA (HL)", "SRA", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x2f, "SRA A", "SRA", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x30, "SWAP B", "SWAP", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x31, "SWAP C", "SWAP", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x32, "SWAP D", "SWAP", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x33, "SWAP E", "SWAP", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x34, "SWAP H", "SWAP", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x35, "SWAP L", "SWAP", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x36, "SWAP (HL)", "SWAP", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x37, "SWAP A", "SWAP", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::ZERO}}, true},
     {0x38, "SRA B", "SRL", {{R::B, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x39, "SRA C", "SRL", {{R::C, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3a, "SRA D", "SRL", {{R::D, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3b, "SRA E", "SRL", {{R::E, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3c, "SRA H", "SRL", {{R::H, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3d, "SRA L", "SRL", {{R::L, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3e, "SRA (HL)", "SRL", {{DR{FR::HL}, {}}}, 1, {{{}, {}}}, 0, 2, 4, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x3f, "SRA A", "SRL", {{R::A, {}}}, 1, {{{}, {}}}, 0, 2, 2, 0, J::ALWAYS, {{F::Z, F::ZERO, F::ZERO, F::A0}}, true},
     {0x40, "BIT 0, B", "BIT_GET", {{R::B, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x41, "BIT 0, C", "BIT_GET", {{R::C, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x42, "BIT 0, D", "BIT_GET", {{R::D, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x43, "BIT 0, E", "BIT_GET", {{R::E, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x44, "BIT 0, H", "BIT_GET", {{R::H, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x45, "BIT 0, L", "BIT_GET", {{R::L, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x46, "BIT 0, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{0, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x47, "BIT 0, A", "BIT_GET", {{R::A, {}}}, 1, {{0, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A0, F::ZERO, F::ONE, _}}, true},
     {0x48, "BIT 1, B", "BIT_GET", {{R::B, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x49, "BIT 1, C", "BIT_GET", {{R::C, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4a, "BIT 1, D", "BIT_GET", {{R::D, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4b, "BIT 1, E", "BIT_GET", {{R::E, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4c, "BIT 1, H", "BIT_GET", {{R::H, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4d, "BIT 1, L", "BIT_GET", {{R::L, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4e, "BIT 1, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{1, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x4f, "BIT 1, A", "BIT_GET", {{R::A, {}}}, 1, {{1, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A1, F::ZERO, F::ONE, _}}, true},
     {0x50, "BIT 2, B", "BIT_GET", {{R::B, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x51, "BIT 2, C", "BIT_GET", {{R::C, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x52, "BIT 2, D", "BIT_GET", {{R::D, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x53, "BIT 2, E", "BIT_GET", {{R::E, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x54, "BIT 2, H", "BIT_GET", {{R::H, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x55, "BIT 2, L", "BIT_GET", {{R::L, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x56, "BIT 2, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{2, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x57, "BIT 2, A", "BIT_GET", {{R::A, {}}}, 1, {{2, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A2, F::ZERO, F::ONE, _}}, true},
     {0x58, "BIT 3, B", "BIT_GET", {{R::B, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x59, "BIT 3, C", "BIT_GET", {{R::C, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5a, "BIT 3, D", "BIT_GET", {{R::D, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5b, "BIT 3, E", "BIT_GET", {{R::E, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5c, "BIT 3, H", "BIT_GET", {{R::H, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5d, "BIT 3, L", "BIT_GET", {{R::L, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5e, "BIT 3, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{3, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x5f, "BIT 3, A", "BIT_GET", {{R::A, {}}}, 1, {{3, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A3, F::ZERO, F::ONE, _}}, true},
     {0x60, "BIT 4, B", "BIT_GET", {{R::B, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x61, "BIT 4, C", "BIT_GET", {{R::C, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x62, "BIT 4, D", "BIT_GET", {{R::D, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x63, "BIT 4, E", "BIT_GET", {{R::E, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x64, "BIT 4, H", "BIT_GET", {{R::H, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x65, "BIT 4, L", "BIT_GET", {{R::L, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x66, "BIT 4, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{4, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x67, "BIT 4, A", "BIT_GET", {{R::A, {}}}, 1, {{4, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A4, F::ZERO, F::ONE, _}}, true},
     {0x68, "BIT 5, B", "BIT_GET", {{R::B, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x69, "BIT 5, C", "BIT_GET", {{R::C, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6a, "BIT 5, D", "BIT_GET", {{R::D, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6b, "BIT 5, E", "BIT_GET", {{R::E, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6c, "BIT 5, H", "BIT_GET", {{R::H, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6d, "BIT 5, L", "BIT_GET", {{R::L, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6e, "BIT 5, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{5, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x6f, "BIT 5, A", "BIT_GET", {{R::A, {}}}, 1, {{5, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A5, F::ZERO, F::ONE, _}}, true},
     {0x70, "BIT 6, B", "BIT_GET", {{R::B, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x71, "BIT 6, C", "BIT_GET", {{R::C, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x72, "BIT 6, D", "BIT_GET", {{R::D, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x73, "BIT 6, E", "BIT_GET", {{R::E, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x74, "BIT 6, H", "BIT_GET", {{R::H, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x75, "BIT 6, L", "BIT_GET", {{R::L, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x76, "BIT 6, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{6, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x77, "BIT 6, A", "BIT_GET", {{R::A, {}}}, 1, {{6, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A6, F::ZERO, F::ONE, _}}, true},
     {0x78, "BIT 7, B", "BIT_GET", {{R::B, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x79, "BIT 7, C", "BIT_GET", {{R::C, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7a, "BIT 7, D", "BIT_GET", {{R::D, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7b, "BIT 7, E", "BIT_GET", {{R::E, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7c, "BIT 7, H", "BIT_GET", {{R::H, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7d, "BIT 7, L", "BIT_GET", {{R::L, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7e, "BIT 7, (HL)", "BIT_GET", {{DR{FR::HL}, {}}}, 1, {{7, 0}}, 1, 2, 3, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x7f, "BIT 7, A", "BIT_GET", {{R::A, {}}}, 1, {{7, 0}}, 1, 2, 2, 0, J::ALWAYS, {{F::NOT_A7, F::ZERO, F::ONE, _}}, true},
     {0x80, "RES 0, B", "BIT_SET", {{R::B, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x81, "RES 0, C", "BIT_SET", {{R::C, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x82, "RES 0, D", "BIT_SET", {{R::D, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x83, "RES 0, E", "BIT_SET", {{R::E, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x84, "RES 0, H", "BIT_SET", {{R::H, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x85, "RES 0, L", "BIT_SET", {{R::L, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x86, "RES 0, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{0, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x87, "RES 0, A", "BIT_SET", {{R::A, {}}}, 1, {{0, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x88, "RES 1, B", "BIT_SET", {{R::B, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x89, "RES 1, C", "BIT_SET", {{R::C, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8a, "RES 1, D", "BIT_SET", {{R::D, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8b, "RES 1, E", "BIT_SET", {{R::E, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8c, "RES 1, H", "BIT_SET", {{R::H, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8d, "RES 1, L", "BIT_SET", {{R::L, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8e, "RES 1, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{1, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x8f, "RES 1, A", "BIT_SET", {{R::A, {}}}, 1, {{1, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x90, "RES 2, B", "BIT_SET", {{R::B, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x91, "RES 2, C", "BIT_SET", {{R::C, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x92, "RES 2, D", "BIT_SET", {{R::D, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x93, "RES 2, E", "BIT_SET", {{R::E, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x94, "RES 2, H", "BIT_SET", {{R::H, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x95, "RES 2, L", "BIT_SET", {{R::L, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x96, "RES 2, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{2, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x97, "RES 2, A", "BIT_SET", {{R::A, {}}}, 1, {{2, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x98, "RES 3, B", "BIT_SET", {{R::B, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x99, "RES 3, C", "BIT_SET", {{R::C, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9a, "RES 3, D", "BIT_SET", {{R::D, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9b, "RES 3, E", "BIT_SET", {{R::E, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9c, "RES 3, H", "BIT_SET", {{R::H, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9d, "RES 3, L", "BIT_SET", {{R::L, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9e, "RES 3, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{3, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0x9f, "RES 3, A", "BIT_SET", {{R::A, {}}}, 1, {{3, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa0, "RES 4, B", "BIT_SET", {{R::B, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa1, "RES 4, C", "BIT_SET", {{R::C, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa2, "RES 4, D", "BIT_SET", {{R::D, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa3, "RES 4, E", "BIT_SET", {{R::E, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa4, "RES 4, H", "BIT_SET", {{R::H, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa5, "RES 4, L", "BIT_SET", {{R::L, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa6, "RES 4, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{4, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa7, "RES 4, A", "BIT_SET", {{R::A, {}}}, 1, {{4, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa8, "RES 5, B", "BIT_SET", {{R::B, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xa9, "RES 5, C", "BIT_SET", {{R::C, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xaa, "RES 5, D", "BIT_SET", {{R::D, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xab, "RES 5, E", "BIT_SET", {{R::E, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xac, "RES 5, H", "BIT_SET", {{R::H, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xad, "RES 5, L", "BIT_SET", {{R::L, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xae, "RES 5, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{5, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xaf, "RES 5, A", "BIT_SET", {{R::A, {}}}, 1, {{5, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb0, "RES 6, B", "BIT_SET", {{R::B, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb1, "RES 6, C", "BIT_SET", {{R::C, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb2, "RES 6, D", "BIT_SET", {{R::D, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb3, "RES 6, E", "BIT_SET", {{R::E, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb4, "RES 6, H", "BIT_SET", {{R::H, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb5, "RES 6, L", "BIT_SET", {{R::L, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb6, "RES 6, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{6, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb7, "RES 6, A", "BIT_SET", {{R::A, {}}}, 1, {{6, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb8, "RES 7, B", "BIT_SET", {{R::B, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xb9, "RES 7, C", "BIT_SET", {{R::C, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xba, "RES 7, D", "BIT_SET", {{R::D, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xbb, "RES 7, E", "BIT_SET", {{R::E, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xbc, "RES 7, H", "BIT_SET", {{R::H, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xbd, "RES 7, L", "BIT_SET", {{R::L, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xbe, "RES 7, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{7, 0}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xbf, "RES 7, A", "BIT_SET", {{R::A, {}}}, 1, {{7, 0}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc0, "SET 0, B", "BIT_SET", {{R::B, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc1, "SET 0, C", "BIT_SET", {{R::C, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc2, "SET 0, D", "BIT_SET", {{R::D, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc3, "SET 0, E", "BIT_SET", {{R::E, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc4, "SET 0, H", "BIT_SET", {{R::H, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc5, "SET 0, L", "BIT_SET", {{R::L, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc6, "SET 0, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{0, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc7, "SET 0, A", "BIT_SET", {{R::A, {}}}, 1, {{0, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc8, "SET 1, B", "BIT_SET", {{R::B, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xc9, "SET 1, C", "BIT_SET", {{R::C, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xca, "SET 1, D", "BIT_SET", {{R::D, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xcb, "SET 1, E", "BIT_SET", {{R::E, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xcc, "SET 1, H", "BIT_SET", {{R::H, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xcd, "SET 1, L", "BIT_SET", {{R::L, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xce, "SET 1, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{1, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xcf, "SET 1, A", "BIT_SET", {{R::A, {}}}, 1, {{1, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd0, "SET 2, B", "BIT_SET", {{R::B, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd1, "SET 2, C", "BIT_SET", {{R::C, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd2, "SET 2, D", "BIT_SET", {{R::D, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd3, "SET 2, E", "BIT_SET", {{R::E, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd4, "SET 2, H", "BIT_SET", {{R::H, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd5, "SET 2, L", "BIT_SET", {{R::L, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd6, "SET 2, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{2, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd7, "SET 2, A", "BIT_SET", {{R::A, {}}}, 1, {{2, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd8, "SET 3, B", "BIT_SET", {{R::B, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xd9, "SET 3, C", "BIT_SET", {{R::C, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xda, "SET 3, D", "BIT_SET", {{R::D, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xdb, "SET 3, E", "BIT_SET", {{R::E, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xdc, "SET 3, H", "BIT_SET", {{R::H, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xdd, "SET 3, L", "BIT_SET", {{R::L, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xde, "SET 3, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{3, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xdf, "SET 3, A", "BIT_SET", {{R::A, {}}}, 1, {{3, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe0, "SET 4, B", "BIT_SET", {{R::B, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe1, "SET 4, C", "BIT_SET", {{R::C, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe2, "SET 4, D", "BIT_SET", {{R::D, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe3, "SET 4, E", "BIT_SET", {{R::E, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe4, "SET 4, H", "BIT_SET", {{R::H, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe5, "SET 4, L", "BIT_SET", {{R::L, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe6, "SET 4, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{4, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe7, "SET 4, A", "BIT_SET", {{R::A, {}}}, 1, {{4, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe8, "SET 5, B", "BIT_SET", {{R::B, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xe9, "SET 5, C", "BIT_SET", {{R::C, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xea, "SET 5, D", "BIT_SET", {{R::D, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xeb, "SET 5, E", "BIT_SET", {{R::E, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xec, "SET 5, H", "BIT_SET", {{R::H, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xed, "SET 5, L", "BIT_SET", {{R::L, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xee, "SET 5, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{5, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xef, "SET 5, A", "BIT_SET", {{R::A, {}}}, 1, {{5, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf0, "SET 6, B", "BIT_SET", {{R::B, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf1, "SET 6, C", "BIT_SET", {{R::C, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf2, "SET 6, D", "BIT_SET", {{R::D, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf3, "SET 6, E", "BIT_SET", {{R::E, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf4, "SET 6, H", "BIT_SET", {{R::H, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf5, "SET 6, L", "BIT_SET", {{R::L, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf6, "SET 6, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{6, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf7, "SET 6, A", "BIT_SET", {{R::A, {}}}, 1, {{6, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf8, "SET 7, B", "BIT_SET", {{R::B, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xf9, "SET 7, C", "BIT_SET", {{R::C, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfa, "SET 7, D", "BIT_SET", {{R::D, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfb, "SET 7, E", "BIT_SET", {{R::E, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfc, "SET 7, H", "BIT_SET", {{R::H, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfd, "SET 7, L", "BIT_SET", {{R::L, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xfe, "SET 7, (HL)", "BIT_SET", {{DR{FR::HL}, {}}}, 1, {{7, 1}}, 2, 2, 4, 0, J::ALWAYS, {{_, _, _, _}}, true},
     {0xff, "SET 7, A", "BIT_SET", {{R::A, {}}}, 1, {{7, 1}}, 2, 2, 2, 0, J::ALWAYS, {{_, _, _, _}}, true}}};
// clang-format on

} // namespace gbemu::backend

#endif // GBEMU_BACKEND_OPCODE_DATA_H
