load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "imgui",
    srcs = [
        "about.cpp",
        "cpu.cpp",
        "debugger.cpp",
        "frontend.cpp",
        "memory.cpp",
        "performance.cpp",
    ],
    hdrs = [
        "about.h",
        "cpu.h",
        "debugger.h",
        "frontend.h",
        "memory.h",
        "performance.h",
        "util.h",
        "window.h",
    ],
    linkopts = select({
        "//conditions:default": [],
        "@bazel_tools//src/conditions:darwin": [
            "-framework",
            "AudioToolbox",
            "-framework",
            "IOKit",
            "-framework",
            "Carbon",
            "-framework",
            "Cocoa",
            "-framework",
            "GameController",
            "-framework",
            "ForceFeedback",
            "-framework",
            "CoreHaptics",
            "-framework",
            "Metal",
            "-framework",
            "CoreVideo",
            "-liconv",
            "-framework",
            "UniformTypeIdentifiers",
            "-framework",
            "AppKit",
        ],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//gbemu/backend",
        "//gbemu/config",
        "//gbemu/frontend",
        "@imgui",
        "@imgui//backends:platform-sdl2",
        "@imgui//backends:renderer-sdl2",
        "@native_file_dialog//:nfd",
        "@sdl2//:SDL2",
    ],
)
